let nhlW = []

// let list5 = []

// for(let i = 0; i < names.length; i++) {
// 	let player = names[i].textContent
// 	if (player.includes('.')) {
// 		var mySubString = player.substring(
//     			player.lastIndexOf(". ", 4) + 2, 
//     			player.lastIndexOf(",")
// 		)
// 		list5.push(mySubString)
// 	}
// }

nhlW[0] = {
    name: 'Bleacher Report',
    job: 'Alan Bass',
    date: '10 Oct 2010',
    players: [
        "Gordie Howe",
        "Maurice Richard",
        "Bobby Hull",
        "Mike Bossy",
        "Jaromir Jagr",
        "Brett Hull",
        "Guy Lafleur",
        "Jari Kurri",
        "Luc Robitaille",
        "Bernie Geoffrion",
        "Brendan Shanahan",
        "Aurele Joliat",
        "Didier Pitre",
        "Busher Jackson",
        "Mark Recchi",
        "John Bucyk",
        "Dave Andreychuk",
        "Mike Gartner",
        "Teemu Selanne",
        "Dickie Moore",
        "Frank Mahovlich",
        "Dit Clapper",
        "Cy Denneny",
        "Babe Dye",
        "Sweeney Schriner",
        "Doug Bentley",
        "Michel Goulet",
        "Dino Ciccarelli",
        "Bob Gainey",
        "Andy Bathgate",
        "Bill Cook",
        "Glenn Anderson",
        "Theo Fleury",
        "David Taylor",
        "Joe Mullen",
        "Alexander Mogilny",
        "Brian Bellows",
        "Rod Gilbert",
        "Steve Larmer",
        "Lanny McDonald",
        "Clark Gillies",
        "Cam Neely",
        "Keith Tkachuk",
        "Pat Verbeek",
        "Daniel Alfredsson",
        "Esa Tikkanen",
        "Alexander Ovechkin",
        "Valeri Kharlamov",
        "Alex Kovalev",
        "Rick Middleton",
        "Kirk Muller",
        "Rick Tocchet",
        "Jarome Iginla",
        "Yvan Cournoyer",
        "Tony Amonte",
        "Peter Bondra",
        "Owen Nolan",
        "Bill Barber",
        "Markus Naslund",
        "Ray Whitney",
        "Dean Prentice",
        "Bill Guerin",
        "Tomas Sandstrom",
        "Slava Kozlov",
        "Ted Lindsay",
        "George Armstrong",
        "Scott Mellanby",
        "John Tonelli",
        "Stephane Richer",
        "John Leclair",
        "Steve Shutt",
        "Wilf Paiement",
        "Ken Hodge",
        "Geoff Courtnall",
        "Steve Thomas",
        "Claude Lemieux",
        "Pavel Bure",
        "Bert Olmstead",
        "Joseph Pronovost",
        "Dave Christian",
        "Marian Hossa",
        "Pavol Demitra",
        "Kevin Dineen",
        "Bryan Hextall",
        "Murray Craven",
        "Patrik Elias",
        "Miroslav Satan",
        "Michael Foligno",
        "Kevin Stevens",
        "Ryan Smyth",
        "Ziggy Palffy",
        "Vic Hadfield",
        "Milan Hejduk",
        "Patrick Marleau",
        "Danny Gare",
        "Martin St. Louis",
        "Shane Doan",
        "Ilya Kovalchuk",
        "Brian Sutter"
      ],
    url: 'https://bleacherreport.com/articles/498074-nhl-the-games-top-100-wingers-of-all-time#slide5',
    pic: 'bleacher'
}



  export {nhlW}